<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Afbeeldingen</name>
   <tag></tag>
   <elementGuidId>53963456-3722-4d6c-8c03-96b5b73d90d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-msb']/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.hdtb-mitem > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6798a131-db79-44fd-a2bd-50efcc4addd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=dummy+image&amp;rlz=1C1CHBF_enMY1040MY1040&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwiCvPLz1OT-AhUwsKQKHaB7CzUQ_AUoAXoECAEQAw</value>
      <webElementGuid>c27ee8d5-ebc5-4055-930d-a132036a732e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hveid</name>
      <type>Main</type>
      <value>CAEQAw</value>
      <webElementGuid>42271ec7-6a5c-4c37-a714-b9c541fab0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Afbeeldingen</value>
      <webElementGuid>56bdba03-a588-47a9-a221-1aba7633cad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-msb&quot;)/div[1]/div[@class=&quot;MUFPAc&quot;]/div[@class=&quot;hdtb-mitem&quot;]/a[1]</value>
      <webElementGuid>f88025d2-16ba-4934-a246-d745a47d3572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-msb']/div/div/div[2]/a</value>
      <webElementGuid>1efe4a06-708a-4a35-96b2-b0f392dc147e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Afbeeldingen')]</value>
      <webElementGuid>732a675c-1b82-4df7-bba9-61c329eacca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alle'])[1]/following::a[1]</value>
      <webElementGuid>cd626bc5-99a5-424a-9ab2-aa3e93e87447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoekmodi'])[1]/following::a[1]</value>
      <webElementGuid>85d7003f-bb9a-4a4c-9ff9-0339a2fada3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping'])[1]/preceding::a[1]</value>
      <webElementGuid>15f011e9-bc7c-4999-a070-97849e9c0ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Video', &quot;'&quot;, 's')])[1]/preceding::a[2]</value>
      <webElementGuid>748b8807-f849-4d8c-877a-5f3c2525b932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Afbeeldingen']/parent::*</value>
      <webElementGuid>22291f6a-8855-4b99-8cac-db96f228e68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=dummy+image&amp;rlz=1C1CHBF_enMY1040MY1040&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwiCvPLz1OT-AhUwsKQKHaB7CzUQ_AUoAXoECAEQAw')]</value>
      <webElementGuid>74287dfd-309b-4553-b553-dfd8cbf79132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>6e3571ff-4e10-44eb-9c8d-c08e412d3da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=dummy+image&amp;rlz=1C1CHBF_enMY1040MY1040&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwiCvPLz1OT-AhUwsKQKHaB7CzUQ_AUoAXoECAEQAw' and (text() = 'Afbeeldingen' or . = 'Afbeeldingen')]</value>
      <webElementGuid>e3cd6d69-9b1b-41b8-968e-e0d99db687e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
