<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Welcome deandanial54gmail.com</name>
   <tag></tag>
   <elementGuidId>73b34629-dc3e-4367-b92b-77400eb1aa1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameofuser</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nameofuser' and (contains(text(), '${username}') or contains(., '${username}'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nameofuser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52dfe288-40b4-4eb1-8a5d-d28786a6be08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>667df789-8173-44c8-bcb9-d86d3db7226b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7fb53750-1fac-497f-bee2-bb7cc9ab3ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameofuser</value>
      <webElementGuid>7540f513-c5f7-4298-bfe3-9cc61330093f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome deandanial54@gmail.com</value>
      <webElementGuid>b10bb47d-4600-4375-b9ee-12f57f24045b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nameofuser&quot;)</value>
      <webElementGuid>0696c6f4-8e30-4f70-a70b-79d81ac15c6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nameofuser']</value>
      <webElementGuid>d08a2403-468a-4c63-b70c-b669ff10e4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarExample']/ul/li[7]/a</value>
      <webElementGuid>0d51e8a9-490d-460c-bfe6-4d70f0ae2ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Welcome deandanial54@gmail.com')]</value>
      <webElementGuid>de0a74a1-502d-41ef-a231-af358529660a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::a[3]</value>
      <webElementGuid>de0670ca-2bf1-4de9-b781-a7b9ff48d52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(current)'])[1]/following::a[6]</value>
      <webElementGuid>b8d2d3bb-a3d8-4ca4-a9b9-e7805131e998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::a[2]</value>
      <webElementGuid>02c045d6-6575-4c5d-9497-6b037ae63305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::a[3]</value>
      <webElementGuid>72301396-83cb-4d18-b454-55125ed5a98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome deandanial54@gmail.com']/parent::*</value>
      <webElementGuid>2c33b400-2da9-4f05-a55e-e185a1c26dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>a23687f7-4429-4b31-8bdf-2d873b713a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>7918d936-407a-455e-8095-143c8372cd00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'nameofuser' and (text() = 'Welcome deandanial54@gmail.com' or . = 'Welcome deandanial54@gmail.com')]</value>
      <webElementGuid>3534b530-4c0f-47cc-84b2-44181b1baed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
