<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit card_card</name>
   <tag></tag>
   <elementGuidId>b5756c80-5701-41db-b057-0490ea30d49e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a29f5da3-818f-4b1e-a553-f10ccfe90ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2af0a169-e241-4a24-933b-8dcfce6377d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e0ccd35f-92b8-450c-a937-94f352a652d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>ae0691bb-0c71-4d05-bcd2-1cd96b9615e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card&quot;)</value>
      <webElementGuid>9699e7e4-5578-4300-978b-2543955cd5c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card']</value>
      <webElementGuid>537795c9-b708-4adc-a7f7-a1bc97ef1b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderModal']/div/div/div[2]/form/div[4]/input</value>
      <webElementGuid>e91fccfe-6dab-4b11-be43-679aac74296b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>1236860e-082e-4b04-ba88-fa46f22c14a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'card']</value>
      <webElementGuid>c82bef0b-5168-4b6f-895f-d406b5ac7d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
